name = "thinkbigprep-website"
compatibility_date = "2024-01-01"

[build]
command = ""

[pages_build_output_dir]
path = "."

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[rules]]
type = "Data"
globs = ["**/*.mp4", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg"]
